#ifndef __TOKEN_H__
#define __TOKEN_H__


typedef enum TokenKind {
  TOKEN_OP_PLUS,
  TOKEN_OP_MINUS,
  TOKEN_OP_ADD,
  TOKEN_OP_INC,
  TOKEN_OP_SUB,
  TOKEN_OP_DEC,
  TOKEN_OP_MUL,
  TOKEN_OP_DIV,
  TOKEN_OP_MOD,
  TOKEN_OP_CMP_LT,
  TOKEN_OP_CMP_LEQ,
  TOKEN_OP_CMP_GT,
  TOKEN_OP_CMP_GEQ,
  TOKEN_OP_CMP_EQ,
  TOKEN_OP_CMP_NEQ,
  TOKEN_OP_LSL,
  TOKEN_OP_LSR,
  TOKEN_OP_ASR,
} TokenKind;


#endif  // __TOKEN_H__
